Repository UniversityOfSaskatchewanCMPT371/term-project-2025-team-2, pull requests merged in 2025-03, with the labels that each got.

#164 Added copyright statement
  src/components/DicomData/TagUpdater.ts
Labels: documentation

#165 Split playwright tests by feature
  .gitignore
  README.md
  anon-file.png
  original-file.png
  package-lock.json
  playwright.config.ts
  screenshots/edited-tag.png
  screenshots/uploaded-file.png
  test-data/test_dicoms/test_dicom1.py
  test-data/test_dicoms/test_dicom_generator.py
  tests/jest/unitTest/example.test.ts
  tests/playwright/auto-anon.spec.ts
  tests/playwright/deleteTag.spec.ts
  tests/playwright/editTag.spec.ts
  tests/playwright/example.spec.ts
  tests/playwright/helpModal.spec.ts
  tests/playwright/navigation.spec.ts
  tests/playwright/settings.spec.ts
  tests/playwright/sidebar.spec.ts
  tests/playwright/upload.spec.ts
Labels: Tests

#173 Create some unit tests for UI components
  tests/jest/unitTest/EmptyTableRow.test.tsx
  tests/jest/unitTest/FileHeader.test.tsx
  tests/jest/unitTest/FileTable.test.tsx
  tests/jest/unitTest/FileTableBody.test.tsx
Labels: Tests

#175 speed up playwright tests
  package.json
  tests/playwright/integrationTests/auto-anon.spec.ts
  tests/playwright/integrationTests/deleteTag.spec.ts
  tests/playwright/integrationTests/editTag.spec.ts
  tests/playwright/integrationTests/helpModal.spec.ts
  tests/playwright/integrationTests/navigation.spec.ts
  tests/playwright/integrationTests/safari.test.ts
  tests/playwright/integrationTests/settings.spec.ts
  tests/playwright/integrationTests/sidebar.spec.ts
  tests/playwright/integrationTests/upload.spec.ts
  tests/playwright/systemTests/seriesAutoAnon.spec.ts
  tests/playwright/systemTests/seriesEdit.spec.ts
  tests/playwright/systemTests/seriesFileNames.spec.ts
  tests/playwright/systemTests/singleFileTags.spec.ts
Labels: Tests

#178 Test/jestcleanup
  tests/jest/unitTest/DicomParserUtils.test.ts
  tests/jest/unitTest/DicomTable.test.tsx
  tests/jest/unitTest/DicomTableBody.test.tsx
  tests/jest/unitTest/DownloadOption.test.tsx
  tests/jest/unitTest/ErrorBoundary.test.tsx
Labels: Tests

#187 Test/jestimprove
  tests/jest/integrationTest/DicomParserUtils.integration.test.ts
  tests/jest/integrationTest/DicomTable.integration.test.tsx
  tests/jest/integrationTest/FileUploader.integration.test.tsx
  tests/jest/unitTest/DicomParserUtils.test.ts
  tests/jest/unitTest/DicomTable.test.tsx
  tests/jest/unitTest/DicomTableBody.test.tsx
  tests/jest/unitTest/DicomTableRow.test.tsx
  tests/jest/unitTest/EmptyTableRow.test.tsx
  tests/jest/unitTest/ErrorBoundary.test.tsx
  tests/jest/unitTest/FileDownLoad.test.ts
  tests/jest/unitTest/HelpModal.test.tsx
  tests/jest/unitTest/Theme.test.tsx
Labels: bug

#189 Feature - show what tags will be anon confirmation window
  package-lock.json
  playwright.config.smoke.ts
  playwright.config.ts
  src/components/DicomData/TableComponents/AnonPopup.tsx
  src/components/DicomData/TableComponents/TableControls.tsx
  src/components/State/Store.tsx
  src/types/DicomTypes.d.ts
  tests/jest/unitTest/AnonPopup.test.tsx
  tests/playwright/integrationTests/auto-anon.spec.ts
  tests/playwright/systemTests/seriesAutoAnon.spec.ts
Labels: enhancement

#197 Test/jest v2
  tests/jest/integrationTest/Business_layer/DicomParserUtils.integration.test.ts
  tests/jest/integrationTest/UI_layer/DicomTable.integration.test.tsx
  tests/jest/integrationTest/UI_layer/FileUploader.integration.test.tsx
  tests/jest/unitTest/Business_layer/AutoClean.test.ts
  tests/jest/unitTest/Business_layer/DicomParserUtils.test.ts
  tests/jest/unitTest/Business_layer/FileDownLoad.test.ts
  tests/jest/unitTest/Business_layer/Store.test.ts
  tests/jest/unitTest/HelpModal.test.tsx
  tests/jest/unitTest/UI_layer/AnonPopup.test.tsx
  tests/jest/unitTest/UI_layer/DicomTable.test.tsx
  tests/jest/unitTest/UI_layer/DicomTableBody.test.tsx
  tests/jest/unitTest/UI_layer/DicomTableRow.test.tsx
  tests/jest/unitTest/UI_layer/DownloadOption.test.tsx
  tests/jest/unitTest/UI_layer/EmptyTableRow.test.tsx
  tests/jest/unitTest/UI_layer/ErrorBoundary.test.tsx
  tests/jest/unitTest/UI_layer/FileHeader.test.tsx
  tests/jest/unitTest/UI_layer/FileNav.test.tsx
  tests/jest/unitTest/UI_layer/FileTable.test.tsx
  tests/jest/unitTest/UI_layer/FileTableBody.test.tsx
  tests/jest/unitTest/UI_layer/FileUploader.test.tsx
  tests/jest/unitTest/UI_layer/Footer.test.tsx
  tests/jest/unitTest/UI_layer/GenButton.test.tsx
  tests/jest/unitTest/UI_layer/GenErrorPage.test.tsx
  tests/jest/unitTest/UI_layer/HelpModal.test.tsx
  tests/jest/unitTest/UI_layer/LoadingScreen.test.tsx
  tests/jest/unitTest/UI_layer/Modal.test.tsx
  tests/jest/unitTest/UI_layer/QuestionModal.test.tsx
  tests/jest/unitTest/UI_layer/Search.test.tsx
  tests/jest/unitTest/UI_layer/TagDictionary.test.tsx
  tests/jest/unitTest/UI_layer/Theme.test.tsx
  tests/jest/unitTest/UI_layer/TopBar.test.tsx
Labels: Tests

#195 Feature id3 -- added download as zip option on the main (not a feature add but just a feature improvement)
  package-lock.json
  package.json
  src/App.tsx
  src/components/DicomData/TableComponents/TableControls.tsx
  test-data/test_dicoms/test_dicom1.dcm
  tests/playwright/systemTests/singleFileTags.spec.ts
Labels: nonfeature requirement

#200 Test/jest alias
  jest.config.ts
  tests/jest/integrationTest/Business_layer/DicomParserUtils.integration.test.ts
  tests/jest/integrationTest/UI_layer/DicomTable.integration.test.tsx
  tests/jest/integrationTest/UI_layer/FileUploader.integration.test.tsx
  tests/jest/unitTest/Business_layer/AutoClean.test.ts
  tests/jest/unitTest/Business_layer/DicomParserUtils.test.ts
  tests/jest/unitTest/Business_layer/FileDownLoad.test.ts
  tests/jest/unitTest/Business_layer/Store.test.ts
  tests/jest/unitTest/Business_layer/TagDictionary.test.ts
  tests/jest/unitTest/UI_layer/AnonPopup.test.tsx
  tests/jest/unitTest/UI_layer/DicomTable.test.tsx
  tests/jest/unitTest/UI_layer/DicomTableBody.test.tsx
  tests/jest/unitTest/UI_layer/DicomTableRow.test.tsx
  tests/jest/unitTest/UI_layer/DownloadOption.test.tsx
  tests/jest/unitTest/UI_layer/EmptyTableRow.test.tsx
  tests/jest/unitTest/UI_layer/ErrorBoundary.test.tsx
  tests/jest/unitTest/UI_layer/FileHeader.test.tsx
  tests/jest/unitTest/UI_layer/FileNav.test.tsx
  tests/jest/unitTest/UI_layer/FileTable.test.tsx
  tests/jest/unitTest/UI_layer/FileTableBody.test.tsx
  tests/jest/unitTest/UI_layer/FileUploader.test.tsx
  tests/jest/unitTest/UI_layer/Footer.test.tsx
  tests/jest/unitTest/UI_layer/GenButton.test.tsx
  tests/jest/unitTest/UI_layer/GenErrorPage.test.tsx
  tests/jest/unitTest/UI_layer/HelpModal.test.tsx
  tests/jest/unitTest/UI_layer/LoadingScreen.test.tsx
  tests/jest/unitTest/UI_layer/Modal.test.tsx
  tests/jest/unitTest/UI_layer/QuestionModal.test.tsx
  tests/jest/unitTest/UI_layer/Search.test.tsx
  tests/jest/unitTest/UI_layer/Theme.test.tsx
  tests/jest/unitTest/UI_layer/TopBar.test.tsx
Labels: Tests

#198 Test: TagUpdater() jest tests
  src/components/DicomData/DicomParserUtils.ts
  test-data/test_dicoms/gen_dicom_files/tagUpdater_testing/test_dicom_0_NameNoID.dcm
  test-data/test_dicoms/gen_dicom_files/tagUpdater_testing/test_dicom_0_editName.dcm
  test-data/test_dicoms/gen_dicom_files/tagUpdater_testing/test_dicom_0_editNameID.dcm
  test-data/test_dicoms/gen_dicom_files/tagUpdater_testing/test_dicom_0_noName.dcm
  test-data/test_dicoms/gen_dicom_files/tagUpdater_testing/test_dicom_AllVRs.dcm
  test-data/test_dicoms/gen_dicom_files/tagUpdater_testing/test_dicom_AllVRs_changeFD.dcm
  test-data/test_dicoms/gen_dicom_files/tagUpdater_testing/test_dicom_AllVRs_changeUL.dcm
  test-data/test_dicoms/gen_dicom_files/tagUpdater_testing/test_dicom_AllVRs_changeUS.dcm
  test-data/test_dicoms/gen_dicom_files/tagUpdater_testing/test_dicom_tagUpdtest.dcm
  test-data/test_dicoms/test_dicom_generator.py
  tests/jest/unitTest/TagUpdater.test.ts
Labels: Tests

#202 Refactor - Standardize exports
  src/App.tsx
  src/components/DicomData/TableComponents/DicomTable.tsx
  src/components/DicomData/TableComponents/DicomTableBody.tsx
  src/components/DicomData/TableComponents/TableControls.tsx
  src/components/DicomData/TableComponents/TableHeader.tsx
  src/components/ErrorHandling/ErrorBoundary.tsx
  src/components/FileHandling/FileHeader.tsx
  src/components/FileHandling/FileTable.tsx
  src/components/FileHandling/FileTableBody.tsx
  src/components/FileHandling/FileUploader.tsx
  src/components/Hooks/useFilteredRows.ts
  src/components/Navigation/Footer.tsx
  src/components/Navigation/Header.tsx
  src/components/Navigation/HiddenTagsOption.tsx
  src/components/Navigation/SeriesControls.tsx
  src/components/Navigation/SettingsModal.tsx
  src/components/Navigation/Sidebar.tsx
  src/components/Navigation/ThemeSelector.tsx
  src/components/Navigation/Topbar.tsx
  src/components/utils/DownloadOption.tsx
  src/components/utils/LoadingScreen.tsx
  src/components/utils/Modals/HelpModal.tsx
  src/components/utils/Modals/Modal.tsx
  src/components/utils/Modals/QuestionModal.tsx
  src/components/utils/Search.tsx
  src/main.tsx
  tests/jest/integrationTest/UI_layer/DicomTable.integration.test.tsx
  tests/jest/integrationTest/UI_layer/FileUploader.integration.test.tsx
  tests/jest/unitTest/UI_layer/DicomTable.test.tsx
  tests/jest/unitTest/UI_layer/DicomTableBody.test.tsx
  tests/jest/unitTest/UI_layer/DownloadOption.test.tsx
  tests/jest/unitTest/UI_layer/ErrorBoundary.test.tsx
  tests/jest/unitTest/UI_layer/FileHeader.test.tsx
  tests/jest/unitTest/UI_layer/FileTable.test.tsx
  tests/jest/unitTest/UI_layer/FileTableBody.test.tsx
  tests/jest/unitTest/UI_layer/FileUploader.test.tsx
  tests/jest/unitTest/UI_layer/Footer.test.tsx
  tests/jest/unitTest/UI_layer/HelpModal.test.tsx
  tests/jest/unitTest/UI_layer/Modal.test.tsx
  tests/jest/unitTest/UI_layer/QuestionModal.test.tsx
  tests/jest/unitTest/UI_layer/Search.test.tsx
  tests/jest/unitTest/UI_layer/TableControls.test.tsx
  tests/jest/unitTest/UI_layer/TopBar.test.tsx
Labels: nonfeature requirement

#217 Feature/improved sidebar - clean up ui
  playwright.config.integration.ts
  playwright.config.regression.ts
  src/App.tsx
  src/components/Auto/AutoClean.ts
  src/components/Auto/TagsAnon.ts
  src/components/DicomData/TableComponents/AnonPopup.tsx
  src/components/DicomData/TableComponents/DicomTable.tsx
  src/components/DicomData/TableComponents/DicomTableBody.tsx
  src/components/DicomData/TableComponents/DicomTableRow.tsx
  src/components/DicomData/TableComponents/TableControls.tsx
  src/components/DicomData/TableComponents/TableHeader.tsx
  src/components/DicomData/TagUpdater.ts
  src/components/FileHandling/FileTableBody.tsx
  src/components/Hooks/useFilteredRows.ts
  src/components/Navigation/Footer.tsx
  src/components/Navigation/SettingsModal.tsx
  src/components/Navigation/SidePanel.tsx
  src/components/Navigation/Sidebar.tsx
  src/components/Navigation/ThemeSelector.tsx
  src/components/State/Store.tsx
  src/components/utils/DownloadOption.tsx
  src/components/utils/LoadingScreen.tsx
  src/components/utils/Modals/HelpModal.tsx
  src/components/utils/Modals/QuestionModal.tsx
  src/components/utils/Search.tsx
  tests/jest/integrationTest/Business_layer/DicomParserUtils.integration.test.ts
  tests/jest/integrationTest/Business_layer/TagUpdater.integration.test.ts
  tests/jest/integrationTest/Business_layer/UpdateAllFiles.integration.test.ts
  tests/jest/unitTest/Business_layer/AutoClean.test.ts
  tests/jest/unitTest/Business_layer/DicomParserUtils.test.ts
  tests/jest/unitTest/Business_layer/FileDownLoad.test.ts
  tests/jest/unitTest/Business_layer/Store.test.ts
  tests/jest/unitTest/UI_layer/AnonPopup.test.tsx
  tests/jest/unitTest/UI_layer/DicomTableRow.test.tsx
  tests/jest/unitTest/UI_layer/EmptyTableRow.test.tsx
  tests/jest/unitTest/UI_layer/HelpModal.test.tsx
  tests/jest/unitTest/UI_layer/TableControls.test.tsx
  tests/jest/unitTest/UI_layer/Theme.test.tsx
  tests/playwright/integrationTests/auto-anon.spec.ts
  tests/playwright/integrationTests/deleteTag.spec.ts
  tests/playwright/integrationTests/editTag.spec.ts
  tests/playwright/integrationTests/helpModal.spec.ts
  tests/playwright/integrationTests/navigation.spec.ts
  tests/playwright/integrationTests/safari.test.ts
  tests/playwright/integrationTests/settings.spec.ts
  tests/playwright/integrationTests/sidebar.spec.ts
  tests/playwright/integrationTests/upload.spec.ts
  tests/playwright/regressionTests/autoEditing.spec.ts
  tests/playwright/smokeTests/smokeTests.spec.ts
  tests/playwright/systemTests/seriesAutoAnon.spec.ts
  tests/playwright/systemTests/seriesEdit.spec.ts
  tests/playwright/systemTests/seriesFileNames.spec.ts
Labels: enhancement, nonfeature requirement

#218 Minor Fix for parser for CT file uploading error
  src/components/DicomData/DicomParserUtils.ts
Labels: bug

#222 add filename that fails to parse error modal
  src/App.tsx
  src/components/FileHandling/FileUploader.tsx
  src/components/State/Store.tsx
Labels: bug

#223 Improve/download naming
  src/components/Auto/AutoClean.ts
  src/components/DicomData/DownloadFuncs.ts
  src/components/DicomData/TableComponents/DicomTable.tsx
  src/components/DicomData/UpdateAllFiles.ts
  tests/jest/unitTest/Business_layer/AutoClean.test.ts
  tests/jest/unitTest/Business_layer/FileDownLoad.test.ts
Labels: nonfeature requirement

#228 add assert function, start adding to code
  before-edit-files.png
  src/App.tsx
  src/Components/Navigation/FileNavigation.tsx
  src/Components/Navigation/Footer.tsx
  src/Components/Navigation/Header.tsx
  src/Components/Navigation/HiddenTagsOption.tsx
  src/Components/Navigation/SeriesControls.tsx
  src/Components/Navigation/SettingsModal.tsx
  src/Components/Navigation/Sidebar.tsx
  src/Components/Navigation/ThemeSelector.tsx
  src/Components/Navigation/Topbar.tsx
  src/Components/utils/DownloadOption.tsx
  src/Components/utils/GenButton.tsx
  src/Components/utils/LoadingScreen.tsx
  src/Components/utils/Modals/HelpModal.tsx
  src/Components/utils/Modals/Modal.tsx
  src/Components/utils/Modals/QuestionModal.tsx
  src/Components/utils/Search.tsx
  src/DataFunctions/DicomData/DicomParserUtils.ts
  src/DataFunctions/DicomData/DownloadFuncs.ts
  src/DataFunctions/DicomData/TagUpdater.ts
  src/DataFunctions/DicomData/UpdateAllFiles.ts
  src/DataFunctions/assert.ts
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
  src/Features/AutoAnonymize/Functions/AutoClean.ts
  src/Features/AutoAnonymize/Functions/TagsAnon.ts
  src/Features/DicomTagTable/Components/DicomTable.tsx
  src/Features/DicomTagTable/Components/DicomTableBody.tsx
  src/Features/DicomTagTable/Components/DicomTableRow.tsx
  src/Features/DicomTagTable/Components/EmptyTableRow.tsx
  src/Features/DicomTagTable/Components/TableControls.tsx
  src/Features/DicomTagTable/Components/TableHeader.tsx
  src/Features/DicomTagTable/Functions/rowUtils.ts
  src/Features/FileHandling/Components/FileHeader.tsx
  src/Features/FileHandling/Components/FileTable.tsx
  src/Features/FileHandling/Components/FileTableBody.tsx
  src/Features/FileHandling/Components/FileUploader.tsx
  src/Hooks/useFilteredRows.ts
  src/State/Store.tsx
  tests/jest/unitTest/Business_layer/Assert.test.ts
  tests/jest/unitTest/Business_layer/FileDownLoad.test.ts
Labels: nonfeature requirement

#231 set zip as default, always show download setting
  jest.config.ts
  playwright.config.ts
  src/App.tsx
  src/Components/Navigation/SettingsModal.tsx
  src/Components/utils/DownloadOption.tsx
  src/DataFunctions/DicomData/DicomParserUtils.ts
  src/DataFunctions/DicomData/DownloadFuncs.ts
  src/DataFunctions/DicomData/UpdateAllFiles.ts
  src/DataFunctions/assert.ts
  src/Features/DicomTagTable/Components/DicomTable.tsx
  src/Features/DicomTagTable/Components/TableControls.tsx
  src/Features/FileHandling/Components/FileUploader.tsx
  src/State/Store.tsx
  tests/jest/integrationTest/Business_layer/TagUpdater.integration.test.ts
  tests/jest/unitTest/Business_layer/Assert.test.ts
  tests/jest/unitTest/Business_layer/AutoClean.test.ts
  tests/jest/unitTest/Business_layer/FileDownLoad.test.ts
  tests/jest/unitTest/UI_layer/DicomTableBody.test.tsx
  tests/playwright/integrationTests/safari.test.ts
  tests/playwright/systemTests/seriesEdit.spec.ts
Labels: enhancement

#232 get rid of type ANY for error and event
  src/Components/ErrorHandling/ErrorBoundary.tsx
  src/Components/utils/DownloadOption.tsx
  src/main.tsx
  src/types/vite-pwa.d.ts
Labels: nonfeature requirement

#234 add file count view, add file move button tooltips
  src/Components/Navigation/FileNavigation.tsx
  src/Features/FileHandling/Components/FileHeader.tsx
  tests/jest/unitTest/UI_layer/FileHeader.test.tsx
Labels: nonfeature requirement

#237 Feature/insert new tag
  src/App.tsx
  src/Components/utils/alertHeader.tsx
  src/DataFunctions/DicomData/TagUpdater.ts
  src/Features/DicomTagTable/Components/DicomTable.tsx
  src/Features/DicomTagTable/Components/DicomTableBody.tsx
  src/Features/DicomTagTable/Components/NewTagRow.tsx
  src/Features/DicomTagTable/Components/TableControls.tsx
  src/Features/DicomTagTable/Functions/rowUtils.ts
  src/Features/DicomTagTable/Types/DicomTypes.d.ts
  src/State/Store.tsx
  tests/jest/integrationTest/Business_layer/TagUpdater.integration.test.ts
  tests/jest/unitTest/Business_layer/Store.test.ts
  tests/jest/unitTest/UI_layer/FileHeader.test.tsx
Labels: enhancement

#236 Fix/jest path alias
  jest.config.ts
  tests/jest/integrationTest/Business_layer/DicomParserUtils.integration.test.ts
  tests/jest/integrationTest/Business_layer/TagUpdater.integration.test.ts
  tests/jest/integrationTest/Business_layer/UpdateAllFiles.integration.test.ts
  tests/jest/integrationTest/UI_layer/DicomTable.integration.test.tsx
  tests/jest/integrationTest/UI_layer/FileUploader.integration.test.tsx
  tests/jest/unitTest/Business_layer/Assert.test.ts
  tests/jest/unitTest/Business_layer/AutoClean.test.ts
  tests/jest/unitTest/Business_layer/DicomParserUtils.test.ts
  tests/jest/unitTest/Business_layer/FileDownLoad.test.ts
  tests/jest/unitTest/Business_layer/Store.test.ts
  tests/jest/unitTest/Business_layer/TagDictionary.test.ts
  tests/jest/unitTest/UI_layer/DicomTable.test.tsx
  tests/jest/unitTest/UI_layer/DicomTableBody.test.tsx
  tests/jest/unitTest/UI_layer/DicomTableRow.test.tsx
  tests/jest/unitTest/UI_layer/DownloadOption.test.tsx
  tests/jest/unitTest/UI_layer/EmptyTableRow.test.tsx
  tests/jest/unitTest/UI_layer/ErrorBoundary.test.tsx
  tests/jest/unitTest/UI_layer/FileHeader.test.tsx
  tests/jest/unitTest/UI_layer/FileNav.test.tsx
  tests/jest/unitTest/UI_layer/FileTable.test.tsx
  tests/jest/unitTest/UI_layer/FileTableBody.test.tsx
  tests/jest/unitTest/UI_layer/FileUploader.test.tsx
  tests/jest/unitTest/UI_layer/Footer.test.tsx
  tests/jest/unitTest/UI_layer/GenButton.test.tsx
  tests/jest/unitTest/UI_layer/GenErrorPage.test.tsx
  tests/jest/unitTest/UI_layer/HelpModal.test.tsx
  tests/jest/unitTest/UI_layer/LoadingScreen.test.tsx
  tests/jest/unitTest/UI_layer/Modal.test.tsx
  tests/jest/unitTest/UI_layer/QuestionModal.test.tsx
  tests/jest/unitTest/UI_layer/Search.test.tsx
  tests/jest/unitTest/UI_layer/TableControls.test.tsx
  tests/jest/unitTest/UI_layer/Theme.test.tsx
  tests/jest/unitTest/UI_layer/TopBar.test.tsx
  tsconfig.app.json
Labels: bug

#239 Feature - Add editing and removing tags from default auto anon tag list
  src/App.tsx
  src/Components/Navigation/AutoAnonTagsEdit.tsx
  src/Components/Navigation/SettingsModal.tsx
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
  src/Features/AutoAnonymize/Functions/AutoClean.ts
  src/Features/DicomTagTable/Components/TableControls.tsx
  src/State/Store.tsx
  tests/jest/unitTest/Business_layer/AutoClean.test.ts
Labels: enhancement

#244 add click and close alert header
  src/App.tsx
  tests/jest/unitTest/UI_layer/DicomTableBody.test.tsx
  tsconfig.app.json
Labels: bug

#247 fix/improve - adding a tag editor function
  src/DataFunctions/DicomData/TagUpdater.ts
  src/Features/AutoAnonymize/Functions/AutoClean.ts
  src/Features/DicomTagTable/Components/NewTagRow.tsx
Labels: bug

#246 Update README.md
  README.md
Labels: bug, documentation

#245 Improve/clean up imports
  src/Components/ErrorHandling/ErrorBoundary.tsx
  src/Components/ErrorHandling/GenErrorPage.tsx
  src/Components/Navigation/AutoAnonTagsEdit.tsx
  src/Components/Navigation/FileNavigation.tsx
  src/Components/Navigation/Header.tsx
  src/Components/Navigation/HiddenTagsOption.tsx
  src/Components/Navigation/SeriesControls.tsx
  src/Components/Navigation/SettingsModal.tsx
  src/Components/Navigation/Sidebar.tsx
  src/Components/Navigation/ThemeSelector.tsx
  src/Components/Navigation/Topbar.tsx
  src/Components/utils/DownloadOption.tsx
  src/Components/utils/GenButton.tsx
  src/Components/utils/Modals/HelpModal.tsx
  src/Components/utils/Modals/Modal.tsx
  src/Components/utils/Modals/QuestionModal.tsx
  src/Components/utils/Search.tsx
  src/DataFunctions/DicomData/DicomParserUtils.ts
  src/DataFunctions/DicomData/DownloadFuncs.ts
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
  src/Features/AutoAnonymize/Functions/AutoClean.ts
  src/Features/DicomTagTable/Components/DicomTable.tsx
  src/Features/DicomTagTable/Components/TableControls.tsx
  src/Features/FileHandling/Components/FileUploader.tsx
  tsconfig.app.json
  vite.config.ts
Labels: enhancement

#249 Create new tag tests - unit and integration tests
  package.json
  screenshot.png
  screenshot2.png
  src/Features/DicomTagTable/Components/NewTagRow.tsx
  tests/jest/unitTest/UI_layer/AddNewTag.test.tsx
  tests/playwright/integrationTests/addtag.spec.ts
  tests/playwright/integrationTests/deleteTag.spec.ts
  tests/playwright/integrationTests/editTag.spec.ts
  tests/playwright/integrationTests/settings.spec.ts
  tests/playwright/integrationTests/sidebar.spec.ts
Labels: Tests

#250 add basic check to find unknown PII in tags when auto anonymizing
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
  src/Features/AutoAnonymize/Functions/TagsAnon.ts
  src/Features/DicomTagTable/Types/DicomTypes.d.ts
Labels: enhancement

#251 add option to add new tag to auot anon list
  src/Components/Navigation/AutoAnonTagsEdit.tsx
  src/Components/Navigation/SettingsModal.tsx
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
  src/Features/DicomTagTable/Components/NewTagRow.tsx
Labels: bug, enhancement, Low Priority

#252 Add log messages to components/functions
  screenshot.png
  screenshot2.png
  src/App.tsx
  src/Components/Navigation/AutoAnonTagsEdit.tsx
  src/Components/Navigation/FileNavigation.tsx
  src/Components/Navigation/Footer.tsx
  src/Components/Navigation/Header.tsx
  src/Components/Navigation/HiddenTagsOption.tsx
  src/Components/Navigation/SeriesControls.tsx
  src/Components/Navigation/SettingsModal.tsx
  src/Components/Navigation/Sidebar.tsx
  src/Components/Navigation/ThemeSelector.tsx
  src/Components/Navigation/Topbar.tsx
  src/Components/utils/DownloadOption.tsx
  src/Components/utils/EditOption.tsx
  src/Components/utils/LoadingScreen.tsx
  src/Components/utils/Search.tsx
  src/Components/utils/alertHeader.tsx
  src/DataFunctions/DicomData/DicomParserUtils.ts
  src/DataFunctions/DicomData/DownloadFuncs.ts
  src/DataFunctions/DicomData/UpdateAllFiles.ts
  src/DataFunctions/TagDictionary/dictionary.ts
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
  src/Features/AutoAnonymize/Functions/AutoClean.ts
  src/Features/DicomTagTable/Components/DicomTable.tsx
  src/Features/DicomTagTable/Components/DicomTableBody.tsx
  src/Features/DicomTagTable/Components/DicomTableRow.tsx
  src/Features/DicomTagTable/Components/EmptyTableRow.tsx
  src/Features/DicomTagTable/Components/NewTagRow.tsx
  src/Features/DicomTagTable/Components/TableControls.tsx
  src/Features/DicomTagTable/Components/TableHeader.tsx
  src/Features/DicomTagTable/Functions/rowUtils.ts
  src/Features/FileHandling/Components/FileHeader.tsx
  src/Features/FileHandling/Components/FileTable.tsx
  src/Features/FileHandling/Components/FileTableBody.tsx
  src/Features/FileHandling/Components/FileUploader.tsx
  src/Hooks/useFilteredRows.ts
  tests/jest/unitTest/UI_layer/DicomTableBody.test.tsx
  tests/jest/unitTest/UI_layer/EmptyTableRow.test.tsx
  tests/playwright/integrationTests/addtag.spec.ts
Labels: nonfeature requirement

#253 Unit Tests for auto anon tag list edit functions
  screenshot.png
  tests/jest/unitTest/UI_layer/AutoAnonTagsEdit.test.tsx
Labels: Tests

#254 integration tests for edit auot anon list
  tests/playwright/integrationTests/autoAnonListAddTag.spec.ts
  tests/playwright/integrationTests/autoAnonListEditTagValue.spec.ts
  tests/playwright/integrationTests/autoAnonListRemoveTag.spec.ts
Labels: Tests

#255 Improve/update files loading
  src/Components/Navigation/SeriesControls.tsx
  src/Components/utils/DownloadOption.tsx
  src/Components/utils/EditOption.tsx
  src/Components/utils/LoadingScreen.tsx
  src/Components/utils/Search.tsx
  src/DataFunctions/DicomData/DownloadFuncs.ts
  src/DataFunctions/DicomData/UpdateAllFiles.ts
  src/DataFunctions/TagDictionary/dictionary.ts
  src/DataFunctions/assert.ts
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
  tests/jest/unitTest/UI_layer/AddNewTag.test.tsx
  tests/playwright/systemTests/seriesAutoAnon.spec.ts
Labels: enhancement

#256 add more alert popups for user info
  src/Components/Navigation/AutoAnonTagsEdit.tsx
  src/Components/utils/alertHeader.tsx
  src/Features/DicomTagTable/Components/NewTagRow.tsx
  src/Features/DicomTagTable/Components/TableControls.tsx
  src/State/Store.tsx
  tests/jest/unitTest/UI_layer/AutoAnonTagsEdit.test.tsx
  tests/playwright/integrationTests/autoAnonListAddTag.spec.ts
  tests/playwright/integrationTests/autoAnonListEditTagValue.spec.ts
  tests/playwright/integrationTests/autoAnonListRemoveTag.spec.ts
Labels: enhancement

#257 define anys in dicomdata funcs
  src/DataFunctions/DicomData/DicomParserUtils.ts
  src/DataFunctions/DicomData/DownloadFuncs.ts
  src/DataFunctions/DicomData/UpdateAllFiles.ts
  src/Features/DicomTagTable/Types/DicomTypes.d.ts
  tests/jest/integrationTest/Business_layer/UpdateAllFiles.integration.test.ts
  tests/jest/integrationTest/UI_layer/FileUploader.integration.test.tsx
  tests/jest/unitTest/Business_layer/FileDownLoad.test.ts
Labels: bug, High Priority

#258 Fix/auto anon clear updates to tag values between file
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
Labels: bug

#259 Fix on the nested tags display
  src/DataFunctions/DicomData/DicomParserUtils.ts
  src/Features/DicomTagTable/Components/DicomTableRow.tsx
  tests/jest/integrationTest/Business_layer/DicomParserUtils.integration.test.ts
Labels: bug

#260 auto anonymize tags based on current file, not just first file
  src/Features/AutoAnonymize/Functions/AutoClean.ts
Labels: bug

#261 add special debug optional messages to tag updater functions
  src/DataFunctions/DicomData/TagUpdater.ts
  src/Features/DicomTagTable/Components/DicomTableRow.tsx
  src/Hooks/useFilteredRows.ts
Labels: Tests

#264 add option to uplaod a folder of file and folders
  src/Components/Navigation/AutoAnonTagsEdit.tsx
  src/Components/utils/LoadingScreen.tsx
  src/Components/utils/alertHeader.tsx
  src/DataFunctions/DicomData/DicomParserUtils.ts
  src/DataFunctions/DicomData/DownloadFuncs.ts
  src/DataFunctions/DicomData/TagUpdater.ts
  src/DataFunctions/DicomData/UpdateAllFiles.ts
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
  src/Features/AutoAnonymize/Functions/AutoClean.ts
  src/Features/DicomTagTable/Components/DicomTableRow.tsx
  src/Features/DicomTagTable/Components/NewTagRow.tsx
  src/Features/FileHandling/Components/FileUploader.tsx
  src/State/Store.tsx
  tests/jest/integrationTest/Business_layer/UpdateAllFiles.integration.test.ts
  tests/jest/integrationTest/UI_layer/FileUploader.integration.test.tsx
  tests/jest/unitTest/UI_layer/AutoAnonTagsEdit.test.tsx
  tests/jest/unitTest/UI_layer/FileUploader.test.tsx
  tests/playwright/integrationTests/addtag.spec.ts
  tests/playwright/integrationTests/auto-anon.spec.ts
  tests/playwright/integrationTests/deleteTag.spec.ts
  tests/playwright/integrationTests/editTag.spec.ts
  tests/playwright/integrationTests/navigation.spec.ts
  tests/playwright/integrationTests/safari.test.ts
  tests/playwright/integrationTests/sidebar.spec.ts
  tests/playwright/integrationTests/upload.spec.ts
  tests/playwright/regressionTests/autoEditing.spec.ts
  tests/playwright/smokeTests/smokeTests.spec.ts
  tests/playwright/systemTests/seriesAutoAnon.spec.ts
  tests/playwright/systemTests/seriesEdit.spec.ts
  tests/playwright/systemTests/seriesFileNames.spec.ts
Labels: enhancement

#267 download folder structure
  src/Components/Navigation/SeriesControls.tsx
  src/DataFunctions/DicomData/DownloadFuncs.ts
  src/DataFunctions/DicomData/UpdateAllFiles.ts
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
  src/Features/AutoAnonymize/Functions/AutoClean.ts
  src/Features/FileHandling/Components/FileUploader.tsx
  src/Features/FileHandling/Types/FileTypes.d.ts
  src/Hooks/useFilteredRows.ts
  tests/jest/integrationTest/Business_layer/UpdateAllFiles.integration.test.ts
  tests/jest/integrationTest/UI_layer/FileUploader.integration.test.tsx
  tests/jest/unitTest/Business_layer/AutoClean.test.ts
Labels: enhancement

#268 Fix/nested tags search
  src/Hooks/useFilteredRows.ts
Labels: bug

#269 add tag name, loaded from tag dictionary
  playwright.config.integration.ts
  src/Components/Navigation/AutoAnonTagsEdit.tsx
  src/Features/DicomTagTable/Components/NewTagRow.tsx
  src/Hooks/useFilteredRows.ts
  tests/jest/unitTest/Business_layer/AutoClean.test.ts
  tests/playwright/integrationTests/addtag.spec.ts
  tests/playwright/integrationTests/autoAnonListAddTag.spec.ts
  tests/playwright/integrationTests/safari.test.ts
Labels: bug

#279 Add implicit vr support - fix demo CT file errors
  README.md
  package.json
  src/DataFunctions/DicomData/TagUpdater.ts
  src/Features/AutoAnonymize/Functions/AutoClean.ts
  src/Hooks/useFilteredRows.ts
  tests/playwright/integrationTests/addtag.spec.ts
  tests/playwright/integrationTests/autoAnonListAddTag.spec.ts
Labels: bug, enhancement

#280 ensure loading screen is shown/updated while processing files
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
  src/Features/AutoAnonymize/Functions/AutoClean.ts
Labels: bug, enhancement

#283 Fix/folderorder
  src/Components/ErrorHandling/GenErrorPage.tsx
  src/Components/Navigation/FileNavigation.tsx
  src/Components/Navigation/Footer.tsx
  src/Components/Navigation/Header.tsx
  src/Components/Navigation/HiddenTagsOption.tsx
  src/Components/Navigation/SeriesControls.tsx
  src/Components/Navigation/SettingsModal.tsx
  src/Components/Navigation/Sidebar.tsx
  src/Components/Navigation/ThemeSelector.tsx
  src/Components/Navigation/Topbar.tsx
  src/DataFunctions/DicomData/UpdateAllFiles.ts
  src/Features/FileHandling/Components/FileUploader.tsx
  src/State/Store.tsx
  src/types/types.ts
Labels: bug

#285 Done with load testing for the project
  playwright.load.config.ts
  tests/playwright/loadtests/concurrentUsersUpload.spec.ts
  tests/playwright/loadtests/stressTestMultipleTabs.spec.ts
  tests/playwright/loadtests/uploadFolder.spec.ts
  tests/playwright/loadtests/uploadLargeNumberOfFiles.spec.ts
  tests/playwright/loadtests/uploadLoadTest.spec.ts
Labels: Tests

#286 tag dictionary import/export functions
  docker/dev/Dockerfile
  src/Components/Navigation/AutoAnonTagsEdit.tsx
  src/Features/DicomTagTable/Components/NewTagRow.tsx
  src/Features/FileHandling/Components/FileUploader.tsx
  src/Features/TagDictEditor/DictTagsEdit.tsx
  src/Features/TagDictEditor/TagDictTableRow.tsx
  src/Features/TagDictEditor/TagDictionaryTable.tsx
  src/Services/TagDictionaryDB.ts
  src/State/Store.tsx
  tests/jest/unitTest/UI_layer/AddNewTag.test.tsx
  tests/playwright/integrationTests/addtag.spec.ts
  tests/playwright/integrationTests/autoAnonListAddTag.spec.ts
  tests/playwright/integrationTests/autoAnonListEditTagValue.spec.ts
  tests/playwright/integrationTests/autoAnonListRemoveTag.spec.ts
  tests/playwright/integrationTests/navigation.spec.ts
  tests/playwright/integrationTests/safari.test.ts
  tests/playwright/integrationTests/sidebar.spec.ts
  tests/playwright/integrationTests/upload.spec.ts
  tests/playwright/loadtests/concurrentUsersUpload.spec.ts
  tests/playwright/loadtests/stressTestMultipleTabs.spec.ts
  tests/playwright/loadtests/uploadFolder.spec.ts
  tests/playwright/loadtests/uploadLargeNumberOfFiles.spec.ts
  tests/playwright/loadtests/uploadLoadTest.spec.ts
  tests/playwright/systemTests/seriesEdit.spec.ts
  tests/playwright/systemTests/seriesFileNames.spec.ts
Labels: enhancement

#289 Fix: Reduce anys in TagUpdater
  src/DataFunctions/DicomData/TagUpdater.ts
  src/Features/DicomTagTable/Functions/rowUtils.ts
  src/Features/DicomTagTable/Types/DicomTypes.d.ts
Labels: nonfeature requirement

#290 replace some anys
  src/Features/DicomTagTable/Components/DicomTableRow.tsx
Labels: High Priority

#293 Jest test for Tag dictionary DB and editor
  .gitignore
  package.json
  src/Components/utils/LoadingScreen.tsx
  src/Features/DicomTagTable/Components/DicomTableRow.tsx
  src/Features/DicomTagTable/Components/TableControls.tsx
  src/Features/TagDictEditor/DictTagsEdit.tsx
  src/Logger/Logger.ts
  tests/jest/integrationTest/UI_layer/DictTagsEdit.integration.test.tsx
  tests/jest/unitTest/Services/TagDictionaryDB.test.ts
  tests/jest/unitTest/UI_layer/TagDictionaryTable.test.tsx
Labels: bug, Tests

#296 add tests for low coverage functions, newtagrow, usefilterrows, helpmodal
  tests/jest/unitTest/UI_layer/AddNewTag.test.tsx
  tests/jest/unitTest/UI_layer/HelpModal.test.tsx
  tests/jest/unitTest/hooks/useFilterRows.test.ts
Labels: Tests

#299 Test/jest - improve code coverage (downloader, uploader, controls)
  tests/jest/integrationTest/Business_layer/UploadFolder.integration.test.ts
  tests/jest/unitTest/Business_layer/FileDownLoad.test.ts
  tests/jest/unitTest/UI_layer/TableControls.test.tsx
Labels: Tests

#300 Test add new tag
  tests/jest/unitTest/Business_layer/AddTag.test.ts
Labels: Tests

#302 Testing find pii
  tests/jest/unitTest/UI_layer/FindPII.test.tsx
Labels: Tests

#301 added some system tests - playwright - file upload, navigation, validation
  test-data/invalid_files/sample.txt
  tests/playwright/systemTests/autoAnonValidation.spec.ts
  tests/playwright/systemTests/invalidFileUpload.spec.ts
  tests/playwright/systemTests/navigateFiles.spec.ts
  tests/playwright/systemTests/uploadAndVerify.spec.ts
Labels: Tests

#303 Test/cleanup
  tests/jest/unitTest/Business_layer/AddTag.test.ts
Labels: Tests, Low Priority

#304 Testing auto anom
  tests/jest/integrationTest/Business_layer/AutoAnon.integration.test.ts
  tests/jest/unitTest/UI_layer/FindPII.test.tsx
Labels: Tests

#308 HotFIx - fix auto anon, files with dif tags
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
  src/Features/AutoAnonymize/Functions/AutoClean.ts
Labels: bug, High Priority

#309 exclude the Vite entry and root from Jest coverage
  jest.config.ts
Labels: Tests

#314 Improve test coverage
  tests/jest/unitTest/UI_layer/HiddenTagsOption.test.tsx
  tests/jest/unitTest/UI_layer/SeriesControls.test.tsx
  tests/jest/unitTest/UI_layer/SettingsModal.test.tsx
  tests/jest/unitTest/UI_layer/Sidebar.test.tsx
Labels: Tests

#315 Add option to show auto updated tags on files in normal file editor before downloading
  jest.config.ts
  src/DataFunctions/DicomData/FileProcessor.ts
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
  src/Features/AutoAnonymize/Functions/AutoClean.ts
  src/Features/DicomTagTable/Components/DicomTableBody.tsx
  tests/jest/integrationTest/Business_layer/UploadFolder.integration.test.ts
  tests/jest/unitTest/Business_layer/FileDownLoad.test.ts
  tests/jest/unitTest/UI_layer/AddNewTag.test.tsx
  tests/jest/unitTest/UI_layer/HelpModal.test.tsx
  tests/jest/unitTest/UI_layer/HiddenTagsOption.test.tsx
  tests/jest/unitTest/UI_layer/SeriesControls.test.tsx
  tests/jest/unitTest/UI_layer/SettingsModal.test.tsx
  tests/jest/unitTest/UI_layer/Sidebar.test.tsx
  tests/jest/unitTest/UI_layer/TableControls.test.tsx
  tests/jest/unitTest/hooks/useFilterRows.test.ts
  tests/playwright/systemTests/autoAnonValidation.spec.ts
  tests/playwright/systemTests/invalidFileUpload.spec.ts
  tests/playwright/systemTests/navigateFiles.spec.ts
  tests/playwright/systemTests/uploadAndVerify.spec.ts
Labels: enhancement

#316 fix delete tag UI
  src/DataFunctions/DicomData/TagUpdater.ts
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
  src/Features/DicomTagTable/Components/DicomTableRow.tsx
  src/Features/DicomTagTable/Functions/rowUtils.ts
  src/Features/DicomTagTable/Types/DicomTypes.d.ts
  tests/playwright/integrationTests/deleteTag.spec.ts
Labels: bug, High Priority

#320 Feature/found pii pagination
  src/Components/Navigation/AutoAnonTagsEdit.tsx
  src/DataFunctions/DicomData/DicomParserUtils.ts
  src/Features/AutoAnonymize/Components/AutoConfirmPanel.tsx
  src/Features/AutoAnonymize/Components/PIIResultsTable.tsx
  src/Features/AutoAnonymize/Functions/PIIDetection.ts
  src/Services/TagDictionaryDB.ts
  src/Services/standardDataElements.ts
  src/State/Store.tsx
  tests/jest/unitTest/Services/TagDictionaryDB.test.ts
Labels: bug, enhancement, Low Priority

#321 make question modal modular, reusable
  src/App.tsx
  src/Components/Navigation/Sidebar.tsx
  src/Components/utils/Modals/HelpModal.tsx
  src/Components/utils/Modals/QuestionModal.tsx
  src/State/QuestionModalStore.ts
  src/State/Store.tsx
  src/types/types.ts
  tests/jest/unitTest/UI_layer/HelpModal.test.tsx
  tests/jest/unitTest/UI_layer/QuestionModal.test.tsx
  tests/jest/unitTest/UI_layer/Sidebar.test.tsx
  tests/jest/unitTest/state/QuestionModalStore.test.ts
  tests/jest/unitTest/state/Store.test.ts
Labels: nonfeature requirement

#324 Jest/fileuploader
  jest.config.ts
  tests/jest/unitTest/UI_layer/FileUploader.test.tsx
Labels: Tests

#325 Fix/loading screen update
  jest.config.ts
  package-lock.json
  package.json
  src/App.tsx
  src/Components/Navigation/Sidebar.tsx
  src/DataFunctions/DicomData/UpdateAllFiles.ts
  src/Features/DicomTagTable/Components/DicomTable.tsx
  src/Features/FileHandling/Components/FileUploader.tsx
  src/Services/standardDataElements.ts
  stats.html
  tests/jest/integrationTest/UI_layer/DicomTable.integration.test.tsx
  tests/jest/integrationTest/UI_layer/FileUploader.integration.test.tsx
  tests/jest/unitTest/UI_layer/DicomTable.test.tsx
  tests/jest/unitTest/UI_layer/FileUploader.test.tsx
  tests/jest/unitTest/UI_layer/Sidebar.test.tsx
  vite.config.ts
Labels: bug, Low Priority

#327 Test/refactor - add auto anon test, refactor playwright tests(make smaller)
  tests/jest/integrationTest/UI_layer/AutoAnontagsEdit.integration.test.tsx
  tests/jest/unitTest/UI_layer/autoconfirmpanel.test.tsx
  tests/playwright/integrationTests/autoAnonListEditTagValue.spec.ts
Labels: Tests
