Repository UniversityOfSaskatchewanCMPT371/term-project-2025-team-2, pull requests merged in 2025-04, with the labels that each got.

#328 fix lost files, in folders
  src/App.tsx
  src/DataFunctions/DicomData/DownloadFuncs.ts
  src/DataFunctions/DicomData/FileProcessor.ts
  src/DataFunctions/DicomData/UpdateAllFiles.ts
  src/Features/FileHandling/Components/FileUploader.tsx
  src/Features/FileHandling/Types/FileTypes.d.ts
  src/State/Store.tsx
  tests/jest/integrationTest/Business_layer/UpdateAllFiles.integration.test.ts
  tests/jest/integrationTest/Business_layer/UploadFolder.integration.test.ts
  tests/jest/integrationTest/UI_layer/FileUploader.integration.test.tsx
  tests/jest/unitTest/Business_layer/FileDownLoad.test.ts
  tests/jest/unitTest/state/Store.test.ts
  tests/playwright/systemTests/seriesEdit.spec.ts
Labels: bug, High Priority

#330 Fix/dependabot
  .github/dependabot.yml
  .github/workflows/regression_test.yml
Labels: infrastructure

#331 Fix: New tag's name from 'Add tag' showed up as "name"
  src/Features/DicomTagTable/Functions/rowUtils.ts
Labels: bug

#335 Hotfix where trigger for regression test not working
  .github/workflows/regression_test.yml
Labels: infrastructure
