Repository UniversityOfSaskatchewanCMPT371/term-project-2025-team-2, pull requests merged in 2025-02, with the labels that each got.

#59 add JSDoc comments and tests for LoadTags Class
  loader/loader.js
  package.json
  remote_logger/readme.md
  tests/loader_test.js
  webpack.config.js
Labels: Tests

#65 Qunit integration test
  loader/loader.js
  tests/IM0
  tests/integration_test.js
  tests/test_runner.html
Labels: Tests

#70 quick fix on testing file numbers
  tests/integration_test.js
Labels: bug, Tests

#71 remove file location selection, save log messages in memory and downl…
  dev/docker-compose.yml
  index.html
  logger/logger.js
  script.js
  tests/test_runner.html
  tests/uitests.spec.js
Labels: nonfeature requirement

#72 add dicom parser library files to project
  dev/Dockerfile
  dicomParser/LICENSE
  dicomParser/README.md
  dicomParser/src/.gitattributes
  dicomParser/src/alloc.js
  dicomParser/src/bigEndianByteArrayParser.js
  dicomParser/src/byteArrayParser.js
  dicomParser/src/byteStream.js
  dicomParser/src/dataSet.js
  dicomParser/src/findAndSetUNElementLength.js
  dicomParser/src/findEndOfEncapsulatedPixelData.js
  dicomParser/src/findItemDelimitationItem.js
  dicomParser/src/index.js
  dicomParser/src/littleEndianByteArrayParser.js
  dicomParser/src/parseDicom.js
  dicomParser/src/parseDicomDataSet.js
  dicomParser/src/readDicomElementExplicit.js
  dicomParser/src/readDicomElementImplicit.js
  dicomParser/src/readEncapsulatedImageFrame.js
  dicomParser/src/readEncapsulatedPixelData.js
  dicomParser/src/readEncapsulatedPixelDataFromFragments.js
  dicomParser/src/readPart10Header.js
  dicomParser/src/readSequenceElementExplicit.js
  dicomParser/src/readSequenceElementImplicit.js
  dicomParser/src/readSequenceItem.js
  dicomParser/src/readTag.js
  dicomParser/src/sharedCopy.js
  dicomParser/src/util/createJPEGBasicOffsetTable.js
  dicomParser/src/util/dataSetToJS.js
  dicomParser/src/util/elementToString.js
  dicomParser/src/util/index.js
  dicomParser/src/util/parseDA.js
  dicomParser/src/util/parseTM.js
  dicomParser/src/util/util.js
  dicomParser/src/version.js
  eslint.config.mjs
  index.html
  loader/loader.js
  service-worker.js
  tests/uitests.spec.js
Labels: nonfeature requirement

#74 Feature/nested tags display
  eslint.config.mjs
  index.html
  loader/loader.js
  script.js
  styles.css
  tagEditor/tagEditor.js
  tests/loader_test.js
  tests/logger_test.js
  tests/run_browser_test.js
  tests/test_runner.html
Labels: enhancement

#85 hotfix on ReadUnit32 failing on certain X-Ray files
  src/components/DicomData/DicomParserUtils.tsx
  src/components/DicomData/DicomTable.tsx
Labels: bug

#88 add button to show/hide tags as marked as hidden
  src/components/DicomData/DicomParserUtils.tsx
  src/components/DicomData/DicomTable.tsx
  src/types/types.ts
Labels: enhancement

#93 mark changed values as red
  src/App.tsx
  src/components/DicomData/DicomParserUtils.tsx
  src/components/DicomData/DicomTable.tsx
  src/components/DicomData/DicomTableRow.tsx
  src/components/ErrorHandling/ErrorBoundary.tsx
  src/components/ErrorHandling/GenErrorPage.tsx
  src/components/Navigation/Sidebar.tsx
  src/components/utils/HelpIcon.tsx
Labels: enhancement

#92 bug/fix display issue when show hidden tags
  src/components/DicomData/DicomTable.tsx
Labels: bug

#97 add heroIcon library, clean up components, put all types in types.tsx…
  package-lock.json
  package.json
  src/App.tsx
  src/components/DicomData/DicomParserUtils.tsx
  src/components/DicomData/DicomTable.tsx
  src/components/DicomData/DicomTableRow.tsx
  src/components/ErrorHandling/ErrorBoundary.tsx
  src/components/ErrorHandling/GenErrorPage.tsx
  src/components/FileHandling/FileHeader.tsx
  src/components/FileHandling/FileTable.tsx
  src/components/FileHandling/FileTableBody.tsx
  src/components/FileHandling/FileUploader.tsx
  src/components/Navigation/FileNavigation.tsx
  src/components/Navigation/Sidebar.tsx
  src/components/Navigation/ThemeSelector.tsx
  src/components/Navigation/Topbar.tsx
  src/components/utils/GenButton.tsx
  src/components/utils/IconButton.tsx
  src/components/utils/Modal.tsx
  src/components/utils/QuestionModal.tsx
  src/components/utils/Search.tsx
  src/types/types.ts
Labels: nonfeature requirement

#101 Fea/UI
  src/App.tsx
  src/components/FileHandling/FileTable.tsx
  src/components/FileHandling/FileTableBody.tsx
  src/components/FileHandling/FileUploader.tsx
  src/components/Navigation/Sidebar.tsx
  src/components/Navigation/Topbar.tsx
  src/components/utils/GenButton.tsx
  src/types/types.ts
Labels: enhancement

#103 improve nested tags display in the table
  src/components/DicomData/DicomTableRow.tsx
  src/types/types.ts
Labels: enhancement

#105 Fix/remove cached dev dist files
  .gitignore
  dev-dist/sw.js
  dev-dist/sw.js.map
Labels: bug, nonfeature requirement

#108 Feature/basic tag updater
  eslint.config.js
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  playwright.config.ts
  src/App.tsx
  src/components/DicomData/DicomParserUtils.tsx
  src/components/DicomData/DicomTable.tsx
  src/components/DicomData/DicomTableRow.tsx
  src/components/DicomData/TagUpdater.tsx
  src/components/FileHandling/FileTable.tsx
  src/components/FileHandling/FileTableBody.tsx
  src/components/FileHandling/FileUploader.tsx
  src/components/Navigation/Sidebar.tsx
  src/components/Navigation/ThemeSelector.tsx
  src/components/Navigation/Topbar.tsx
  src/main.tsx
  src/types/types.ts
  src/types/vite-pwa.d.ts
  tests/jest/FileUploader.test.tsx
  tests/jest/example.test.ts
  tsconfig.json
  vite.config.ts
Labels: enhancement

#111 let user know about tags edited as series if multiple files edited as single
  src/App.tsx
  src/components/utils/QuestionModal.tsx
  src/types/types.ts
Labels: nonfeature requirement

#114 Feature/apply edits multifiles
  src/App.tsx
  src/components/DicomData/DicomTable.tsx
  src/components/DicomData/TagUpdater.tsx
  src/components/Navigation/Sidebar.tsx
Labels: enhancement

#116 Refactor/types logger clean up
  README.md
  docs/assets/style.css
  src/App.tsx
  src/components/DicomData/DicomParserUtils.tsx
  src/components/DicomData/DicomTable.tsx
  src/components/DicomData/DicomTableRow.tsx
  src/components/DicomData/TagUpdater.tsx
  src/components/ErrorHandling/GenErrorPage.tsx
  src/components/FileHandling/FileHeader.tsx
  src/components/FileHandling/FileTable.tsx
  src/components/FileHandling/FileTableBody.tsx
  src/components/FileHandling/FileUploader.tsx
  src/components/Navigation/FileNavigation.tsx
  src/components/Navigation/Sidebar.tsx
  src/components/Navigation/ThemeSelector.tsx
  src/components/utils/Logger.tsx
  src/output.css
  src/types/DicomTypes.d.ts
  src/types/FileTypes.d.ts
  src/types/types.ts
Labels: nonfeature requirement

#117 Fix: Display double and uint16 tag values correctly
  src/components/DicomData/DicomParserUtils.tsx
  src/tagDictionary/dictionary.tsx
Labels: bug

#118 add loading state when files are being uploaded
  src/App.tsx
  src/components/FileHandling/FileUploader.tsx
  src/types/FileTypes.d.ts
  tests/jest/FileUploader.test.tsx
Labels: enhancement

#121 add package for tooltips, add some tooltips
  package-lock.json
  package.json
  src/components/DicomData/DicomTableRow.tsx
  src/components/Navigation/Sidebar.tsx
  src/components/Navigation/ThemeSelector.tsx
  src/components/Navigation/Topbar.tsx
  src/main.tsx
Labels: enhancement

#126 test/create dicom table and table row tests
  jest.setup.ts
  src/components/DicomData/DicomTable.tsx
  src/components/DicomData/DicomTableRow.tsx
  src/types/DicomTypes.d.ts
  tests/jest/DicomTable.test.tsx
  tests/jest/DicomTableRow.test.tsx
Labels: Tests

#133 Testing checks for playwright test
  tests/playwright/example.spec.ts
Labels: Tests

#147 Upload to display sys test
  package-lock.json
  package.json
  requirements-dev.txt
  test-data/test_dicoms/test_dicom1.dcm
  test-data/test_dicoms/test_dicom1.py
  tests/playwright/uploadToTable_sys_test.spec.ts
Labels: Tests

#150 add playwright deps to dev container
  docker/dev/Dockerfile
  docker/dev/docker-compose.yml
  package.json
Labels: nonfeature requirement, infrastructure
